### ISSUE TITLE
Crash on undefined body

### ISSUE THREAD

**Issue by yoh-there** [randallagordon/node-nma#2]
I got this

> TypeError: Cannot read property 'indexOf' of undefined
>     at Request._callback (/volume1/homes/admin/.node-red/node_modules/node-red-node-nma/node_modules/nma/lib/nma.js:24:13)
>     at self.callback (/volume1/homes/admin/.node-red/node_modules/node-red-node-nma/node_modules/nma/node_modules/request/request.js:364:22)

I am not 100% sure but I think it happened when my ISP decided to do maintenance (it happened at exactly 01:00 AM). It also crashed my entire node-red instance. I have changed line 24 to...

> if (typeof body == "string" && body.indexOf("success code=\"200\" remaining") !== -1) {

...in the hope this will prevent further problems.

**Comment by randallagordon** [comment]
Thanks for reporting, that is indeed a nasty oversight! Albeit a tiny change, if you're interested in adding a green box to your GitHub profile, I'd gladly accept a PR. Otherwise I'll try to get around to adding it in and publishing a new version soon. Been meaning to do a v1.0.0 anywho!

**Comment by yoh-there** [comment]
There you go!

**Comment by randallagordon** [comment]
Awesome, thanks much! I'll get a v1.0.0 published soon!
